name: Build TermuOS

on:
    push:
        branches:
            - main
            - dev
            - feat/**
        pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt install -y \
                    clang \
                    lld \
                    nasm \
                    xorriso \
                    mtools \
                    git

            - name: Clone Limine
              run: |
                git clone https://github.com/limine-bootloader/limine.git --branch=v8.x-binary --depth=1

            - name: Build ISO
              run: make

            - name: Upload ISO artifact
              uses: actions/upload-artifact@v4
              with:
                name: termuos-iso
                path: termuos.iso